<a href="https://colab.research.google.com/github/Denise-Pro/Case_DataEngineer_Confitec/blob/main/Desafio_Multiplica%C3%A7%C3%A3o_Matriz_Quadrada/TESTEPYSPARK_Confitect_Matrizez.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Intalando a Biblioteca principal, caso ela já não esteja disponível no ambiente

In [1]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


## Importando apenas as funções que serão necessárias

In [1]:
from numpy import random, dot, array, reshape
from math import sqrt

## Esta primeira função está programada para fazer o produto de Matriz Quadrada entre Matrizes Idênticas, que foram geradas através de números aleatórios

É necessário passar para ela, em sua chamada, o número mínimo e máximo do intervalo de onde serão gerados os números aleatórios, bem como o tamanho que se espera dessas Matrizes.


In [2]:
def multiplica_matrizes_iguais(de, ate, n):
  if isinstance(de, int) and isinstance(ate, int) and isinstance(n, int) and de>=0 and ate > de and n>=0:
    x = random.randint(de,ate, (n,n))
    a = x
    b = x
    produto = dot(x,x)
    print('\n A e B são matrizes {}x{}'.format(n,n))
    print('A=\n{}\n'.format(a))
    print('B=\n{}\n'.format(b))
    print('Product=\n{}'.format(produto))
    return '\n Produto Matriz Quadrada, entre matrizes idênticas, Realizado com Sucesso'
  else:
    return "\n Apenas Números Inteiros e positivos serão aceitos"

## Já esta segunda função calcula o Produto de Matriz Quadrada entre Matrizes diferentes, que também foram geradas a partir de números aleatórios

Também é necessário passar para ela, em sua chamada, o número mínimo e máximo do intervalo de onde serão gerados os números aleatórios, bem como o número de colunas da primeira Matriz e de linhas da segunda.
Lembrando que o produto de Matriz Quadrada só é possível quando o número de colunas da primeira Matriz é igual ao número de linhas da segunda.

In [3]:
def multiplica_matrizes_diferentes(de, ate, n):
  if isinstance(de, int) and isinstance(ate, int) and isinstance(n, int) and de>=0 and ate > de and n>=0:
    if n == 0:
      n = n+1
    if de > n:
      i = de
      de = n
      n = i
    m1 = random.randint(de,n) 
    m2 = random.randint(de,n)
    print('\nA é uma matriz {}x{}'.format(m1,n))
    print('\nB é uma matriz {}x{}\n'.format(n,m2))
    a = random.randint(de,ate, (m1,n))
    b = random.randint(de,ate, (n,m2))
    produto = dot(a,b)
    print('A=\n{}\n'.format(a))
    print('B=\n{}\n'.format(b))
    print('Product=\n{}'.format(produto))
    return '\n Produto Matriz Quadrada, entre matrizes diferentes, Realizado com Sucesso'
  else:
    return "\n O segundo número precisa ser maior do que o primeiro e apenas números inteiros e positivos serão aceitos"

## Já esta terceira função tem por objetivo chamar uma das duas outras funções caso o usuário queira trabalhar com valores aleatórios ou, também, fornecer o cálculo entre matrizes idênticas em que o próprio usuário pode colocar os elementos que deseja usar no produto.

In [4]:
def calcula_matriz_quadrada():

  print("Você gostaria de fazer esse cálculo para matrizes iguais ou diferentes?\n")
  tipoMatriz = int(input('Digite 1 para Matrizes idênticas e 2 para Matrizes Diferentes: '))

  if tipoMatriz == 1:
    print('\nVocê gostaria de passar os elementos da Matriz para o cálculo?\n')
    tipoCalculo = int(input('Digite 1 para passar um intervalo com cada um dos elementos e 2 para que sejam elementos aleatórios: '))
    if tipoCalculo == 2:
      de = int(input('\n Digite o limite mínimo do intervalo: '))
      ate = int(input('\n Digite o limite máximo do intervalo: '))
      n = int(input('\n Digite o número de linhas e colunas, um único número: '))
      return multiplica_matrizes_iguais(de, ate, n)
    elif tipoCalculo == 1:
      sequencia = array(list(map(int, input("\n Digite os elementos numéricos e separados por vírgula: ").split(","))))
      size = sqrt(len(sequencia))
      try:
        matriz = sequencia.reshape(int(size), int(size))
        print('A=\n{}\n'.format(matriz))
        print('B=\n{}\n'.format(matriz))
        print('Product=')
        return dot(matriz,matriz)
      except ValueError:
        return "\n O Número de elementos não é suficiente para o cálculo de matriz quadrada"
  if tipoMatriz == 2:
    de = int(input('\nDigite o limite mínimo do intervalo: '))
    ate = int(input('\nDigite o limite máximo do intervalo: '))
    n = int(input('\nDigite o número de colunas de A e linhas de B, um único número: '))
    return multiplica_matrizes_diferentes(de, ate, n)

In [5]:
calcula_matriz_quadrada()

Você gostaria de fazer esse cálculo para matrizes iguais ou diferentes?

Digite 1 para Matrizes idênticas e 2 para Matrizes Diferentes: 1

Você gostaria de passar os elementos da Matriz para o cálculo?

Digite 1 para passar um intervalo com cada um dos elementos e 2 para que sejam elementos aleatórios: 1

 Digite os elementos numéricos e separados por vírgula: 1,2,3,4,5,6,7,8,1,2,3,4,5,6,7,8
A=
[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]

B=
[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]

Product=


array([[ 34,  44,  54,  64],
       [ 82, 108, 134, 160],
       [ 34,  44,  54,  64],
       [ 82, 108, 134, 160]])

In [6]:
calcula_matriz_quadrada()

Você gostaria de fazer esse cálculo para matrizes iguais ou diferentes?

Digite 1 para Matrizes idênticas e 2 para Matrizes Diferentes: 1

Você gostaria de passar os elementos da Matriz para o cálculo?

Digite 1 para passar um intervalo com cada um dos elementos e 2 para que sejam elementos aleatórios: 2

 Digite o limite mínimo do intervalo: 0

 Digite o limite máximo do intervalo: 100

 Digite o número de linhas e colunas, um único número: 10

 A e B são matrizes 10x10
A=
[[ 1  4 49 53 89 48 69 10 16 83]
 [31 23 43 76 78  7 43 49 74  5]
 [10 92  2 12 19 86 75 76 31 39]
 [82  2 48 52 90 24 24 24 56 13]
 [76  6 20 47 37 80 88 50 26 57]
 [53 70 89 94 59 31 28 95 66 14]
 [20 84 57 87 30 39  8 52 55 60]
 [80 43 77 38 55  3 21  7 55 45]
 [38 65 24 51 48 84 50  6 48 39]
 [13 48 50 13 52 86  2 63 30 73]]

B=
[[ 1  4 49 53 89 48 69 10 16 83]
 [31 23 43 76 78  7 43 49 74  5]
 [10 92  2 12 19 86 75 76 31 39]
 [82  2 48 52 90 24 24 24 56 13]
 [76  6 20 47 37 80 88 50 26 57]
 [53 70 89 94 59 31 2

'\n Produto Matriz Quadrada, entre matrizes idênticas, Realizado com Sucesso'

In [7]:
calcula_matriz_quadrada()

Você gostaria de fazer esse cálculo para matrizes iguais ou diferentes?

Digite 1 para Matrizes idênticas e 2 para Matrizes Diferentes: 2

Digite o limite mínimo do intervalo: 0

Digite o limite máximo do intervalo: 103

Digite o número de colunas de A e linhas de B, um único número: 5

A é uma matriz 2x5

B é uma matriz 5x4

A=
[[12 14 68 54 98]
 [31 50 67 22 84]]

B=
[[ 24   1  11  34]
 [ 13  74  71  49]
 [ 17  19  28 100]
 [ 13  78  50  59]
 [ 15  44  47  22]]

Product=
[[ 3798 10864 10336 13236]
 [ 4079 10416 10815 13350]]


'\n Produto Matriz Quadrada, entre matrizes diferentes, Realizado com Sucesso'

In [141]:
# def multiplica_matrizes_identicas(*elements):
#     size = sqrt(len(elements))
#     if size.is_integer():
#       matriz = array(elements).reshape(int(size), int(size))
#       # matriz = elements.reshape(int(size), int(size))
#       print('A=\n{}\n'.format(matriz))
#       print('B=\n{}\n'.format(matriz))
#       print('Product=')
#       return dot(matriz,matriz)
#     else:
#       raise RuntimeError("Número de elementos não é suficiente para o cálculo de matriz quadrada")